version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build Project
          command: echo "Building the project"
      - run:
          name: Deploy Project
          command: |
            echo "Deploying the project"
            rsync -avz -e "ssh -p 22" ./project-directory/ username@103.151.111.182:/path/to/deploy/
      - run:
          name: Run Tests
          command: echo "Running tests"

workflows:
  version: 2
  build_deploy_test:
    jobs:
      - build
