version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build Project
          command: echo "Building the project"
      - run:
          name: Deploy Project
          command: echo "Deploying the project"
      - run:
          name: Run Tests
          command: echo "Running tests"

workflows:
  version: 2
  build_deploy_test:
    jobs:
      - build
